main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # it calls view as: detail(request=<HttpRequest object>, question_id=34)
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

open_csv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls'))
]

main/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

main/views.py
from django.shortcuts import render, HttpResponse, Http404, get_object_or_404, HttpResponseRedirect
from .models import Question
from django.urls import reverse

# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    return render(request, template_name='main/index.html', context={"latest_question_list": latest_question_list})

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'main/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'main/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, NameError):
        # Redisplay the question voting form.
        return render(request, 'main/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('main:results', args=(question.id,)))

main/templates/main/detail.html
{% extends 'main/header.html' %}

{% block content %}
    <strong>Detail.html</strong>
    <br>
    <h4>{{ question.question_text }}</h4>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'main:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}


            <label for="choice{{ forloop.counter }}">
            <input class="with-gap" name="choice" type="radio" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
            <span><strong style="color: #4a148c">{{ choice.choice_text }}</strong></span>
            </label>

            <br>

    {% endfor %}
    <br>
    <button class="btn waves-effect waves-light" type="submit" name="action">Vote
    </button>
         
    </form>
{% endblock %}

main/templates/main/header.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>  
        <title>{% block title %}{% endblock %}</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/css/materialize.css' %}">
        <script type="text/javascript" src="{% static 'main/js/bin/materialize.min.js' %}"></script>
        <!-- this is used for sticky footer -->
        <style>
            body {
                display: flex;
                min-height: 100vh;
                flex-direction: column;
            }

            main {
                flex: 1 0 auto;
            }
        </style>
    </head>

    <body>
        {% include 'main/include/navbar.html' %}
        <main>
            <div class="container">
                {% block content %}

                {% endblock %}
            </div>
        </main>
        {% include 'main/include/footer.html' %}
    </body>
</html>

main/templates/main/include/footer.html
<footer id = "footer" class="page-footer teal darken-3">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Aa gaye niche</h5>
                <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any valuable feedback would help support and continue development on this project and is greatly appreciated.</p>
            </div>

            <div class="col l3 s12">
                <h5 class="white-text">Settings</h5>
                <ul>
                        <li><a class="white-text" href="#!">Link 1</a></li>
                        <li><a class="white-text" href="#!">Link 2</a></li>
                        <li><a class="white-text" href="#!">Link 3</a></li>
                        <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Company</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Careers</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Our Team</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">More</a></li>
                </ul>
            </div>
        </div>
    </div>
   
       

    <div class="footer-copyright pink darken-3">
        <div class="container">
            © 2019 SKY All rights reserved
            <a class="grey-text text-lighten-4 right" href="#!">&nbsp;Terms of Use </a>
            <a class="grey-text text-lighten-4 right" href="#!">| Privacy Policy |</a>
        </div>
    </div>
</footer>

main/templates/main/include/navbar.html
<nav>

        <div class="nav-wrapper teal darken-3">
            <div class="container">
              <a href="/main" class="brand-logo">Home</a>
              <a href="/main" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
              <ul class="right hide-on-med-and-down">
                <li><a href="sass.html">Sass</a></li>
                <li><a href="badges.html">Components</a></li>
                <li><a href="collapsible.html">Javascript</a></li>
                <li><a href="mobile.html">Mobile</a></li>
              </ul>
            </div>
        </div>

      </nav>
    
      <ul class="sidenav" id="mobile-demo">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
    

main/templates/main/index.html
{% extends 'main/header.html' %}

{% block content %}
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}

        <li><a href="{% url 'main:detail' question.id %}"><h4  style="color: black;">{{ forloop.counter }}.&nbsp;{{ question.question_text }}</h4></a></li>
            
        <!-- <li><a href="/main/ question.id /">question.question_text</a></li> -->
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

{% endblock %}

main/templates/main/results.html
{% extends 'main/header.html' %}

{% block content %}
    results.html
    <br>
    <ul class="collection with-header">
            <li class="collection-header"><h4>{{question.id}}).&nbsp;{{ question.question_text }}</h4></li>
            {% for choice in question.choice_set.all %}
                <li class="collection-item">
                    <div>
                        {{ choice.choice_text }}
                        <a href="#!" class="secondary-content">
                            <span class="new badge" data-badge-caption="Votes">{{ choice.votes }}</span>
                            </a>
                    </div>
                </li>
            {% endfor %}
    </ul>
    <center>
    <a href="{% url 'main:detail' question.id %}" class="waves-effect waves-light btn">Vote again?</a>
</center>
    {% endblock %}